/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.it.uniba.minima.GUI;

import javax.swing.*;
import java.awt.*;

/**
 * Author: Avventura-nella-piramide-egizia
 */
public class HelpGUI extends JFrame {
    private static HelpGUI instance;

    /**
     * Creates new form HelpGUI
     */
    private HelpGUI() {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    public static HelpGUI getInstance() {
        if (instance == null) {
            instance = new HelpGUI();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        JLabel listaComandi = new javax.swing.JLabel();

        setTitle("Guida Comandi");
        setPreferredSize(new java.awt.Dimension(500, 340));
        setMaximumSize(new java.awt.Dimension(500, 340));
        setMinimumSize(new java.awt.Dimension(500, 340));
        setResizable(false);
        getContentPane().setBackground(new Color(204, 173, 27));
        setIconImage(new ImageIcon("docs/img/gameIcon.jpg").getImage());

        Font font = new Font("Papyrus", Font.BOLD, 12);
        listaComandi.setOpaque(true);
        listaComandi.setBackground(new Color(204, 173, 27));
        listaComandi.setForeground(Color.WHITE);
        listaComandi.setFont(font);
        listaComandi.setBorder(BorderFactory.createMatteBorder(5, 5, 5, 5, new Color(107, 90, 13)));
        listaComandi.setText(
                "<html>" +
                        "Ecco la lista dei comandi:<br>" +
                        "AIUTO<br>" +
                        "NORD<br>" +
                        "SUD<br>" +
                        "EST<br>" +
                        "OVEST<br>" +
                        "OSSERVA<br>" +
                        "INVENTARIO<br>" +
                        "PRENDI<br>" +
                        "LASCIA<br>" +
                        "USA<br>" +
                        "UNISCI<br>" +
                        "PARLA<br>" +
                        "DAI" +
                        "</html>"
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listaComandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(listaComandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
