/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.it.uniba.minima.GUI;

/**
 *
 * @author miche
 */
public class ImpiccatoGUI extends javax.swing.JPanel {

    /**
     * Creates new form cryptedTextGUI
     */
    public ImpiccatoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(440, 400));
        setMinimumSize(new java.awt.Dimension(440, 400));
        setPreferredSize(new java.awt.Dimension(440, 400));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setText("<html><center>__ _____ _____ ________ __ _______</center></html>");
        jLabel1.setIconTextGap(1);
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 301));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 301));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 301));
        jLabel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(95, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(51, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private static javax.swing.JLabel jLabel1;
    // End of variables declaration

    public void setLabelText(String text) {
        jLabel1.setText("<html><center>" + text + "</center></html>");
    }

    public static void setLetter(int i, char c, String phrase) {
        String currentText = jLabel1.getText().replaceAll("<[^>]*>", "");
        StringBuilder newText = new StringBuilder(currentText);
        if (phrase.charAt(i) == ' ') {
            newText.setCharAt(i, ' ');
        } else {
            newText.setCharAt(i, c);
        }

        jLabel1.setText("<html><center>" + newText.toString() + "</center></html>");
    }

    public static void setPhrase(String phrase) {
        jLabel1.setText("<html><center>" + phrase + "</center></html>");
    }
}
