package org.it.uniba.minima.GUI;
import javax.swing.*;
import javax.swing.plaf.basic.BasicProgressBarUI;
import java.awt.*;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyChangeListener;

/**
 * ProgressBarGUI is a custom JPanel that displays a progress bar with a running animation.
 * Author: miche
 */
public class ProgressBarGUI extends javax.swing.JPanel {

    private int counter;
    private int x;
    private final ImageIcon img;
    private final PropertyChangeSupport support;
    private JLabel progressBarLabel;

    /**
     * Creates new form ProgressBarGUI
     */
    public ProgressBarGUI() {
        initComponents();
        img = new ImageIcon("docs/img/runningChar.png");
        x = -img.getIconWidth();
        support = new PropertyChangeSupport(this);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        support.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        support.removePropertyChangeListener(listener);
    }

    public void setFinished(boolean isFinished) {
        support.firePropertyChange("isFinished", null, isFinished);
    }

    public void startProgressBar() {
        int imgWidth = 161;
        int panelWidth = runningGIFPanel.getWidth();
        counter = 0;

        Timer timer = new Timer(1, e -> {
            if (counter < 100) {
                counter++;
                progressBar.setValue(counter);
                progressBarLabel.setText("Loading... " + counter + "%");
                x = (int) ((double) counter / 100 * (panelWidth + imgWidth)) - imgWidth;
                runningGIFPanel.repaint();
            } else {
                ((Timer) e.getSource()).stop();
                progressBarLabel.setText("Get Ready to Play!");

                Timer delayTimer = new Timer(1000, e1 -> {
                    ((Timer) e1.getSource()).stop();
                    setFinished(true);
                });
                delayTimer.start();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        runningGIFPanel = new JPanel();
        progressBar = new javax.swing.JProgressBar();
        progressBarLabel = new JLabel("Loading... 0%");

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        backgroundPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon img = new ImageIcon("docs/img/placeholder_immagine sfondo.jpeg");
                Image image = img.getImage();
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };

        runningGIFPanel.setPreferredSize(new Dimension(482, 161));
        runningGIFPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Image image = img.getImage();
                g.drawImage(image, x, 0, 161, getHeight(), this);
            }
        };
        runningGIFPanel.setOpaque(false);

        javax.swing.GroupLayout runningGIFPanelLayout = new javax.swing.GroupLayout(runningGIFPanel);
        runningGIFPanel.setLayout(runningGIFPanelLayout);
        runningGIFPanelLayout.setHorizontalGroup(
                runningGIFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 149, Short.MAX_VALUE)
        );
        runningGIFPanelLayout.setVerticalGroup(
                runningGIFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 161, Short.MAX_VALUE)
        );

        progressBar.setFont(new java.awt.Font("Papyrus", 1, 24));
        progressBar.setForeground(new java.awt.Color(204, 173, 27));
        progressBar.setBackground(new java.awt.Color(107, 90, 13));
        progressBar.setOpaque(true);
        progressBar.setBorder(BorderFactory.createLineBorder(new java.awt.Color(107, 90, 13), 5));
        progressBar.setMaximumSize(new java.awt.Dimension(482, 48));
        progressBar.setMinimumSize(new java.awt.Dimension(482, 48));
        progressBar.setPreferredSize(new java.awt.Dimension(482, 48));
        progressBar.setStringPainted(false); // Disable the default string painting

        // Remove the blue frame by customizing the UI
        progressBar.setUI(new BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(Graphics g, JComponent c) {
                if (!(g instanceof Graphics2D)) {
                    return;
                }

                Insets b = progressBar.getInsets(); // area for border
                int width = progressBar.getWidth();
                int height = progressBar.getHeight();
                int barRectWidth = width - (b.right + b.left);
                int barRectHeight = height - (b.top + b.bottom);

                if (barRectWidth <= 0 || barRectHeight <= 0) {
                    return;
                }

                // Paint the background.
                Graphics2D g2d = (Graphics2D) g;
                g2d.setColor(progressBar.getBackground());
                g2d.fillRect(b.left, b.top, barRectWidth, barRectHeight);

                // Paint the progress bar
                int amountFull = getAmountFull(b, barRectWidth, barRectHeight);

                g2d.setColor(progressBar.getForeground());
                g2d.fillRect(b.left, b.top, amountFull, barRectHeight);
            }
        });

        // Configure the label
        progressBarLabel.setFont(new java.awt.Font("Papyrus", 1, 24));
        progressBarLabel.setForeground(new java.awt.Color(255, 255, 255)); // Set the text color to black
        progressBarLabel.setHorizontalAlignment(SwingConstants.CENTER);

        // Add the label to the progress bar
        progressBar.setLayout(new BorderLayout());
        progressBar.add(progressBarLabel, BorderLayout.CENTER);

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(runningGIFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addContainerGap(300, Short.MAX_VALUE)
                                .addComponent(runningGIFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JPanel runningGIFPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration
}
