package org.it.uniba.minima;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;


public class MenuGUI extends javax.swing.JFrame{


    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        BackGroundPanel = new javax.swing.JPanel()
        {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon img = new ImageIcon("docs/img/placeholder_immagine sfondo.jpeg");
                Image image = img.getImage();
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        NewGame = new javax.swing.JButton();
        NewGame.setAlignmentX(Component.CENTER_ALIGNMENT);
        Sound = new javax.swing.JButton( );
        Help = new javax.swing.JButton();
        Help.setText("?");
        LoadGame = new javax.swing.JButton();
        Credits = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        BackGroundPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        BackGroundPanel.setRequestFocusEnabled(false);

        NewGame.setText("Nuova Partita");
        NewGame.setMaximumSize(new java.awt.Dimension(240, 60));
        NewGame.setMinimumSize(new java.awt.Dimension(240, 60));
        NewGame.setPreferredSize(new java.awt.Dimension(240, 60));
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Sound.setText("\uD83D\uDD0A");
        Sound.setMaximumSize(new java.awt.Dimension(40, 40));
        Sound.setMinimumSize(new java.awt.Dimension(40, 40));
        Sound.setPreferredSize(new java.awt.Dimension(40, 40));
        Sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Help.setMaximumSize(new java.awt.Dimension(40, 40));
        Help.setMinimumSize(new java.awt.Dimension(40, 40));
        Help.setPreferredSize(new java.awt.Dimension(40, 40));
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        LoadGame.setText("Carica Partita");
        LoadGame.setMaximumSize(new java.awt.Dimension(240, 60));
        LoadGame.setMinimumSize(new java.awt.Dimension(240, 60));
        LoadGame.setPreferredSize(new java.awt.Dimension(240, 60));
        LoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Credits.setText("Riconoscimenti");
        Credits.setMaximumSize(new java.awt.Dimension(240, 60));
        Credits.setMinimumSize(new java.awt.Dimension(240, 60));
        Credits.setPreferredSize(new java.awt.Dimension(240, 60));
        Credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackGroundPanelLayout = new javax.swing.GroupLayout(BackGroundPanel);
        BackGroundPanelLayout.setHorizontalGroup(
        	BackGroundPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(BackGroundPanelLayout.createSequentialGroup()
        			.addGroup(BackGroundPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(BackGroundPanelLayout.createSequentialGroup()
        					.addGap(270)
        					.addGroup(BackGroundPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(NewGame, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(LoadGame, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Credits, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(BackGroundPanelLayout.createSequentialGroup()
        					.addGap(25)
        					.addGroup(BackGroundPanelLayout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(Help, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(Sound, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(280))
        );
        BackGroundPanelLayout.setVerticalGroup(
        	BackGroundPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(BackGroundPanelLayout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(Sound, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addGap(12)
        			.addComponent(Help, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
        			.addComponent(NewGame, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addComponent(LoadGame, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addComponent(Credits, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(90))
        );
        BackGroundPanel.setLayout(BackGroundPanelLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    }


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton Sound;
    private javax.swing.JButton Help;
    private javax.swing.JButton LoadGame;
    private javax.swing.JButton Credits;
}
